### ISSUE TITLE
Could this python script can deal with both BEAST1 and BEAST2 output?

### ISSUE THREAD

**Issue by ghost** [evogytis/LogFixer#1]
@evogytis I tried this script using the BEAST2 outputs of log files, and then it printed as follows:
Traceback (most recent call last):
  File "Log_Fixer.py", line 83, in <module>
    if line[0]=='state':
IndexError: list index out of range

**Comment by evogytis** [comment]
It's because BEAST2 log files have a lot more boiler plate material at the beginning. This script was not designed to deal with those.

**Comment by ghost** [comment]
@evogytis thanks for you Kindly reply. Could this script can deal with the outputs of BEAST 1 files that were killed by accidents, for example, no power for the computers to run the xml files that caused the the number states of trees and log are not consistent?

**Comment by evogytis** [comment]
I haven't used it in ages but looking at the code it should be outputting only the intact states that are shared by log and trees files.

**Comment by lixingguang** [comment]
in other words, it will delete the intact states for both of the log and tree files, is that right?

**Comment by ghost** [comment]
in other words, it will delete the incomplete states for both the log and trees files, it is greet, for example, I set the chain length for 100million, and stopped by for example,  62million, and this run can still be used, if the ESSs is good for all parameters, is that right?

**Comment by evogytis** [comment]
Correct, though I think it will create new files in the same directory rather than modifying the log and tree files in-place.
